content:
  providers:
    App\Model\Page:
      type: files
      path: '%kernel.project_dir%/../../'
      #excludes:
      #  - /docs/app

  #copy:
  #  - src: '%kernel.project_dir%/public'
  #    dest: .
  #    fail_if_missing: true
  #    ignore_dot_files: false
  #    excludes:
  #      - '*.php'
